language: node_js

node_js:
  - "12"
  - "10"
  - "8"

services:
  # docker is used for couchdb 2.0 (not currently available as a travis service)
  - docker

env:
  global:
  # - COUCH_URL=http://admin:pass@localhost:5984/medic
  # - API_URL=http://admin:pass@localhost:5988
  - COUCH_NODE_NAME=nonode@nohost
  - HORTI_TEST_APPS=http://admin:pass@localhost:5984/test-horti-app
  - HORTI_TEST_BUILDS=http://admin:pass@localhost:5984/test-medic-builds

before_install:
 - ./tests/env-prep.sh
