language: node_js

node_js:
  - "8"

services:
  # docker is used for couchdb 2.0 (not currently available as a travis service)
  - docker

before_install:
  - docker run -d -p 5984:5984 --name couch couchdb:2
  - echo "Starting CouchDB 2.x"
  - until nc -z localhost 5984; do sleep 1; done
  - echo "CouchDB Started"
